### ISSUE TITLE
Incorrect memoization for predicate  conditional rules

### ISSUE THREAD

**Issue by RedSkotina** [PuerkitoBio/pigeon#14]
If rule contain code predicate returning everytime different result on one text position then memoize can break logic

TestCase peg : https://github.com/RedSkotina/pigeon/blob/bugfix-memoization-predicate/test/memoize_predicate/memoize_predicate.peg
Input string: "aa"
Expected output: ["cond2" "cond1"]
Actual output(with enabled memoize ): no match found  

as i see solutions here: 

-  not memoize rule which has  predicate code as childrens according grammar
-  not memoize rule if some flag returned through parse call on children rules.

 For implementation may require redesign of parse code, so i decide ask your opinion.

**Comment by PuerkitoBio** [comment]
To memoize or not is an option. If you have an "impure" code block for a rule, then all parent rules are also impure, and ultimately memoization is useless, so you shouldn't use that option.

**Comment by RedSkotina** [comment]
but error stilll be error.

**Comment by PuerkitoBio** [comment]
Ok maybe I misunderstood, can you walk me through the issue? You're getting
an error when you parse an input with memoization for that grammar? What's
the exact error you get, and what's the input to reproduce the error?

**Comment by RedSkotina** [comment]
i edited first comment  for input string and output error.
Issue: When "impure" rule is memoized then he can return invalid result when some conditions is changed. 
It is normal behavior , but the user should be warned about this or we must NOT memoize "impure" rules.
Look in pull request

**Comment by PuerkitoBio** [comment]
Right, ok so I think I was understanding correctly - there is no "error" *per se*, but the result may be invalid because some code blocks are not deterministic (given the same input, may not produce the same output). I think this is a terrible characteristic for a grammar (and I'm not sure it makes sense to implement it as a PEG, as it may - and will - backtrack in some cases).

But regardless of all that, to memoize or not is an option. You don't have to give that option to the user of your parser. So if you know that, in your grammar, some rules are "not memoizable", then don't give that option to the users of your parser (that is, keep the package generated by `pigeon` as an internal one, and don't expose the Memoize option in your public API).

**Comment by RedSkotina** [comment]
ok. then please note this in documentation.

**Comment by PuerkitoBio** [comment]
I don't think it's fair to expect the readme for a peg library to be a tutorial on peg. I do link to relevant papers in the godoc, though. I think that should be sufficient.
